name: rhymes_creator
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  auto_route: 9.2.2
  dio: 5.7.0
  get_it: 8.0.0
  retrofit: 4.4.1
  json_annotation: ^4.9.0
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.1.0
  equatable: 2.0.5
  realm: ^20.0.0
  uuid: ^4.5.1
  shared_preferences: ^2.3.2
  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^17.2.3
  flutter_launcher_icons: 0.14.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  auto_route_generator:
  retrofit_generator: 9.1.2
  json_serializable: ^6.8.0
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - .env

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/logo/logo.png"
  windows:
    generate: true
    image_path: "assets/logo/logo.png"
  macos:
    generate: true
    image_path: "assets/logo/logo.png"
